apiVersion: v1
kind: Service
metadata:
  name: mongos
  namespace: mongo
  labels:
    name: mongos
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongos
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongos
  namespace: mongo
spec:
  selector:
    matchLabels:
      role: mongos
  serviceName: mongos
  replicas: 2
  template:
    metadata:
      labels:
        role: mongos
        tier: routers
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: role
                  operator: In
                  values:
                  - mongos
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongos-container
          image: mongo
          command:
            - "mongos"
            - "--port"
            - "27017"
            - "--bind_ip"
            - "0.0.0.0"
            - "--configdb"
            - "configsvr/configsvr-0.configsvr:27019, configsvr-1.configsvr:27019, configsvr-2.configsvr:27019"
          ports:
            - containerPort: 27017
