apiVersion: v1
kind: Service
metadata:
  name: shard2
  namespace: mongo
  labels:
    name: shard2
spec:
  ports:
  - port: 27018
    targetPort: 27018
  clusterIP: None
  selector:
    role: shard2
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: shard2
  namespace: mongo
spec:
  selector:
    matchLabels:
      role: shard2
  serviceName: shard2
  replicas: 3
  template:
    metadata:
      labels:
        role: shard2
        tier: shard
        replicaset: shard2
    spec:
      nodeSelector:
        kubernetes.io/hostname : node01
      terminationGracePeriodSeconds: 10
      containers:
        - name: shard2-container
          image: mongo
          command:
            - "mongod"
            - "--port"
            - "27018"
            - "--bind_ip"
            - "0.0.0.0"
            - "--replSet"
            - "shard2"
            - "--shardsvr"
            - "--dbpath"
            - "/mongo-disk"
          ports:
            - containerPort: 27018
          volumeMounts:
            - name: data
              mountPath: /mongo-disk
  volumeClaimTemplates:
  - metadata:
      name: data
      namespace: mongo
      annotations:
        volume.beta.kubernetes.io/storage-class: "nfs-client"
    spec:
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 1Gi
